apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    service: play-tag
spec:
  selector:
    app: play-tag
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2  # Set the desired number of replicas
  selector:
    matchLabels:
      app: play-tag
  template:
    metadata:
      labels:
        app: play-tag
    spec:
      containers:
        - name: app
          image: jujuyeh/play-tag:latest
          ports:
            - containerPort: 8080

---